# Generated by Django 5.0.7 on 2024-07-19 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistManager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlistManager.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='example_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='groups_with_permission',
            field=models.ManyToManyField(blank=True, null=True, related_name='wishlists', to='wishlistManager.wishlistgroup'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='users_with_permission',
            field=models.ManyToManyField(blank=True, null=True, related_name='wishlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
