# Generated by Django 5.0.7 on 2024-09-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistManager', '0002_alter_category_options_alter_category_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
